echo diff log1
diff server1-log1.out server2-log1.out
diff server1-log1.out server3-log1.out
diff server1-log1.out server4-log1.out
diff server1-log1.out server5-log1.out
echo diff log2
diff server1-log2.out server2-log2.out
diff server1-log2.out server3-log2.out
diff server1-log2.out server4-log2.out
diff server1-log2.out server5-log2.out
echo diff log3
diff server1-log3.out server2-log3.out
diff server1-log3.out server3-log3.out
diff server1-log3.out server4-log3.out
diff server1-log3.out server5-log3.out
echo diff log4
diff server1-log4.out server2-log4.out
diff server1-log4.out server3-log4.out
diff server1-log4.out server4-log4.out
diff server1-log4.out server5-log4.out
echo diff log5
diff server1-log5.out server2-log5.out
diff server1-log5.out server3-log5.out
diff server1-log5.out server4-log5.out
diff server1-log5.out server5-log5.out
echo diff completed!